import type { TechnologyTemplate } from "@/types";

export const TOPIC_CATALOG: ReadonlyArray<TechnologyTemplate> = [
  {
    name: "React",
    description: "Structured React interview roadmap for senior frontend roles",
    color: "#6366f1",
    icon: "Atom",
    sections: [
      {
        title: "Fundamentals",
        description: "Core React building blocks",
        topics: [
          { title: "What is React?" },
          { title: "SPA vs MPA" },
          { title: "Virtual DOM" },
          { title: "Reconciliation" },
          { title: "JSX" },
          { title: "Components" },
          { title: "Functional Components" },
          { title: "Props" },
          { title: "State" },
          { title: "Event Handling" },
          { title: "Conditional Rendering" },
          { title: "Lists" },
          { title: "Keys" },
          { title: "Fragments" },
        ],
      },
      {
        title: "Hooks",
        description: "Built-in hooks and composability",
        topics: [
          { title: "useState" },
          { title: "useEffect" },
          { title: "useLayoutEffect" },
          { title: "useMemo" },
          { title: "useCallback" },
          { title: "useRef" },
          { title: "useContext" },
          { title: "useReducer" },
          { title: "Custom Hooks" },
          { title: "Rules of Hooks" },
        ],
      },
      {
        title: "Routing",
        description: "React Router concepts",
        topics: [
          { title: "BrowserRouter" },
          { title: "Routes" },
          { title: "Route" },
          { title: "Nested Routes" },
          { title: "Outlet" },
          { title: "useNavigate" },
          { title: "useParams" },
          { title: "Search Params" },
          { title: "Protected Routes" },
        ],
      },
      {
        title: "Forms",
        description: "Input handling and validation",
        topics: [
          { title: "Controlled Components" },
          { title: "Uncontrolled Components" },
          { title: "Validation" },
          { title: "React Hook Form" },
          { title: "Form State Management" },
        ],
      },
      {
        title: "State Management",
        description: "Application state patterns",
        topics: [
          { title: "Context API" },
          { title: "Redux" },
          { title: "Redux Toolkit" },
          { title: "Zustand" },
          { title: "State Lifting" },
        ],
      },
      {
        title: "Performance",
        description: "Rendering and delivery optimization",
        topics: [
          { title: "React.memo" },
          { title: "Memoization" },
          { title: "Lazy Loading" },
          { title: "Suspense" },
          { title: "Code Splitting" },
          { title: "Dynamic Imports" },
          { title: "Bundle Optimization" },
          { title: "Render Profiling" },
        ],
      },
      {
        title: "API Calls",
        description: "Data fetching patterns",
        topics: [
          { title: "fetch" },
          { title: "Axios" },
          { title: "Loading State" },
          { title: "Error Handling" },
          { title: "AbortController" },
          { title: "Parallel API Calls" },
          { title: "Request Retry Strategy" },
        ],
      },
      {
        title: "Testing",
        description: "React testing essentials",
        topics: [
          { title: "Jest" },
          { title: "React Testing Library" },
          { title: "Mocking" },
          { title: "Component Testing" },
          { title: "Integration Testing" },
        ],
      },
      {
        title: "Frequently Asked Questions",
        description: "Common React interview prompts",
        topics: [
          { title: "Class Components vs Functional Components" },
          { title: "When to use useMemo" },
          { title: "When to use useCallback" },
          { title: "How reconciliation works" },
          { title: "How keys impact rendering" },
          { title: "Controlled vs uncontrolled trade-offs" },
          { title: "Context vs Redux" },
          { title: "How Suspense differs from loading state" },
        ],
      },
    ],
  },
  {
    name: "Angular",
    description: "Structured Angular interview roadmap for senior frontend roles",
    color: "#dd0031",
    icon: "Spline",
    sections: [
      {
        title: "Fundamentals",
        description: "Framework setup and architecture",
        topics: [
          { title: "Angular Architecture" },
          { title: "Bootstrapping" },
          { title: "Standalone APIs" },
          { title: "NgModules" },
          { title: "CLI" },
          { title: "Templates" },
          { title: "Directives" },
          { title: "Data Binding" },
        ],
      },
      {
        title: "Components",
        description: "Component communication and host APIs",
        topics: [
          { title: "Components" },
          { title: "Inputs" },
          { title: "Outputs" },
          { title: "Content Projection" },
          { title: "HostBinding" },
          { title: "HostListener" },
        ],
      },
      {
        title: "Lifecycle",
        description: "Lifecycle hooks and order",
        topics: [
          { title: "ngOnChanges" },
          { title: "ngOnInit" },
          { title: "ngDoCheck" },
          { title: "ngAfterContentInit" },
          { title: "ngAfterContentChecked" },
          { title: "ngAfterViewInit" },
          { title: "ngAfterViewChecked" },
          { title: "ngOnDestroy" },
        ],
      },
      {
        title: "Change Detection",
        description: "Detection strategies and APIs",
        topics: [
          { title: "Default" },
          { title: "OnPush" },
          { title: "ChangeDetectorRef" },
          { title: "markForCheck" },
          { title: "detectChanges" },
          { title: "trackBy" },
        ],
      },
      {
        title: "Dependency Injection",
        description: "Provider graph and injection model",
        topics: [
          { title: "inject()" },
          { title: "Providers" },
          { title: "Hierarchical DI" },
          { title: "InjectionToken" },
          { title: "Singleton Services" },
        ],
      },
      {
        title: "Routing",
        description: "Router architecture and guards",
        topics: [
          { title: "Lazy Loading" },
          { title: "Guards" },
          { title: "Resolvers" },
          { title: "Child Routes" },
          { title: "Route Parameters" },
        ],
      },
      {
        title: "Forms",
        description: "Angular form systems",
        topics: [
          { title: "Reactive Forms" },
          { title: "Template Forms" },
          { title: "Dynamic Forms" },
          { title: "FormControl" },
          { title: "Custom Validators" },
        ],
      },
      {
        title: "HTTP",
        description: "Request lifecycle and interception",
        topics: [
          { title: "HttpClient" },
          { title: "Interceptors" },
          { title: "Error Handling" },
          { title: "Request Cancellation" },
          { title: "Retry Strategy" },
        ],
      },
      {
        title: "Authentication",
        description: "Angular authentication and authorization basics",
        topics: [
          { title: "Authentication vs Authorization" },
          { title: "JWT" },
          { title: "OAuth 2.0" },
          { title: "Access Tokens" },
          { title: "Refresh Tokens" },
          { title: "Route Guards for Auth" },
          { title: "HTTP Interceptors for Tokens" },
          { title: "Role-based Access Control" },
        ],
      },
      {
        title: "RxJS Integration",
        description: "Reactive stream usage in Angular",
        topics: [
          { title: "Observables" },
          { title: "Subjects" },
          { title: "Async Pipe" },
          { title: "switchMap" },
          { title: "combineLatest" },
          { title: "forkJoin" },
        ],
      },
      {
        title: "Performance",
        description: "Rendering and hydration optimization",
        topics: [
          { title: "Signals" },
          { title: "Deferrable Views" },
          { title: "SSR" },
          { title: "Hydration" },
          { title: "Virtual Scroll" },
        ],
      },
      {
        title: "Testing",
        description: "Angular testing stack",
        topics: [
          { title: "Jasmine" },
          { title: "Karma" },
          { title: "TestBed" },
          { title: "Component Fixture" },
          { title: "HTTP Testing Controller" },
        ],
      },
      {
        title: "Frequently Asked Questions",
        description: "Common Angular interview prompts",
        topics: [
          { title: "Standalone APIs vs NgModules" },
          { title: "OnPush vs Default" },
          { title: "Reactive vs Template Forms" },
          { title: "Guard vs Resolver" },
          { title: "Signals vs RxJS" },
          { title: "How DI hierarchy works" },
          { title: "When to use trackBy" },
          { title: "How Angular handles change detection" },
        ],
      },
    ],
  },
  {
    name: "JavaScript",
    description: "Structured JavaScript interview roadmap",
    color: "#eab308",
    icon: "Braces",
    sections: [
      {
        title: "Fundamentals",
        description: "Execution model essentials",
        topics: [
          { title: "Variables" },
          { title: "Scope" },
          { title: "Hoisting" },
          { title: "Execution Context" },
          { title: "Call Stack" },
        ],
      },
      {
        title: "Functions",
        description: "Function and invocation behavior",
        topics: [
          { title: "Closures" },
          { title: "Higher Order Functions" },
          { title: "Callback Functions" },
          { title: "this" },
          { title: "bind" },
          { title: "call" },
          { title: "apply" },
        ],
      },
      {
        title: "Async JavaScript",
        description: "Concurrency model and async patterns",
        topics: [
          { title: "Event Loop" },
          { title: "Microtasks" },
          { title: "Macrotasks" },
          { title: "Promises" },
          { title: "Async/Await" },
        ],
      },
      {
        title: "Arrays",
        description: "Array transformation and querying",
        topics: [
          { title: "map" },
          { title: "filter" },
          { title: "reduce" },
          { title: "find" },
          { title: "some" },
          { title: "every" },
          { title: "sort" },
        ],
      },
      {
        title: "Objects",
        description: "Object handling and immutability",
        topics: [
          { title: "Destructuring" },
          { title: "Spread" },
          { title: "Rest" },
          { title: "Deep Copy" },
          { title: "Shallow Copy" },
        ],
      },
      {
        title: "ES6+",
        description: "Modern language features",
        topics: [
          { title: "Modules" },
          { title: "Template Literals" },
          { title: "Optional Chaining" },
          { title: "Nullish Coalescing" },
          { title: "Arrow Functions" },
        ],
      },
      {
        title: "Frequently Asked Questions",
        description: "Common JavaScript interview prompts",
        topics: [
          { title: "var vs let vs const" },
          { title: "== vs ===" },
          { title: "How closures work" },
          { title: "How this is determined" },
          { title: "How event loop schedules tasks" },
          { title: "Promise vs async-await trade-offs" },
          { title: "Deep copy approaches" },
          { title: "Difference between map and forEach" },
        ],
      },
    ],
  },
  {
    name: "TypeScript",
    description: "Structured TypeScript interview roadmap",
    color: "#3178c6",
    icon: "FileCode2",
    sections: [
      {
        title: "Fundamentals",
        description: "Core typing model",
        topics: [
          { title: "Types" },
          { title: "Interfaces" },
          { title: "Type Aliases" },
          { title: "Enums" },
          { title: "Union Types" },
          { title: "Intersection Types" },
        ],
      },
      {
        title: "Advanced Types",
        description: "Type-level composition",
        topics: [
          { title: "Generics" },
          { title: "keyof" },
          { title: "typeof" },
          { title: "infer" },
          { title: "Conditional Types" },
          { title: "Mapped Types" },
          { title: "Indexed Access Types" },
          { title: "Template Literal Types" },
        ],
      },
      {
        title: "Utility Types",
        description: "Built-in utility toolbox",
        topics: [
          { title: "Partial" },
          { title: "Required" },
          { title: "Pick" },
          { title: "Omit" },
          { title: "Record" },
          { title: "Exclude" },
          { title: "Extract" },
          { title: "Readonly" },
        ],
      },
      {
        title: "Type Safety",
        description: "Safe narrowing and assertions",
        topics: [
          { title: "Narrowing" },
          { title: "Type Guards" },
          { title: "Assertions" },
          { title: "Unknown" },
          { title: "Never" },
        ],
      },
      {
        title: "Frequently Asked Questions",
        description: "Common TypeScript interview prompts",
        topics: [
          { title: "Interface vs type alias" },
          { title: "Any vs unknown" },
          { title: "Type assertions vs type guards" },
          { title: "When to use generics" },
          { title: "How conditional types work" },
          { title: "Mapped types use cases" },
          { title: "How utility types reduce duplication" },
          { title: "Structural typing in TypeScript" },
        ],
      },
    ],
  },
  {
    name: "RxJS",
    description: "Structured RxJS interview roadmap",
    color: "#b7178c",
    icon: "Activity",
    sections: [
      {
        title: "Observables",
        description: "Observable model fundamentals",
        topics: [
          { title: "Observable" },
          { title: "Observer" },
          { title: "Subscription" },
          { title: "Cold vs Hot" },
          { title: "Unsubscription" },
        ],
      },
      {
        title: "Subjects",
        description: "Multicasting primitives",
        topics: [
          { title: "Subject" },
          { title: "BehaviorSubject" },
          { title: "ReplaySubject" },
          { title: "AsyncSubject" },
          { title: "Subject vs BehaviorSubject" },
        ],
      },
      {
        title: "Transformation",
        description: "Projection and flattening",
        topics: [
          { title: "map" },
          { title: "switchMap" },
          { title: "mergeMap" },
          { title: "concatMap" },
          { title: "exhaustMap" },
        ],
      },
      {
        title: "Combination",
        description: "Composing multiple streams",
        topics: [
          { title: "combineLatest" },
          { title: "forkJoin" },
          { title: "zip" },
          { title: "merge" },
          { title: "withLatestFrom" },
        ],
      },
      {
        title: "Filtering",
        description: "Filtering and stream completion",
        topics: [
          { title: "filter" },
          { title: "take" },
          { title: "takeUntil" },
          { title: "debounceTime" },
          { title: "distinctUntilChanged" },
        ],
      },
      {
        title: "Error Handling",
        description: "Resilience and teardown",
        topics: [
          { title: "catchError" },
          { title: "retry" },
          { title: "finalize" },
          { title: "throwError" },
          { title: "Error Recovery Strategy" },
        ],
      },
      {
        title: "Frequently Asked Questions",
        description: "Common RxJS interview prompts",
        topics: [
          { title: "Cold vs hot observables" },
          { title: "switchMap vs mergeMap" },
          { title: "concatMap vs exhaustMap" },
          { title: "Subject vs BehaviorSubject" },
          { title: "combineLatest vs forkJoin" },
          { title: "When to use takeUntil" },
          { title: "How to avoid memory leaks" },
          { title: "Async pipe vs manual subscribe" },
        ],
      },
    ],
  },
  {
    name: "HTML",
    description: "Semantic markup and accessibility essentials",
    color: "#e34f26",
    icon: "FileText",
    sections: [
      {
        title: "Document Structure",
        description: "Markup fundamentals",
        topics: [
          { title: "Doctype" },
          { title: "html Element" },
          { title: "head Element" },
          { title: "body Element" },
          { title: "Meta Tags" },
          { title: "Title Tag" },
          { title: "Semantic HTML" },
          { title: "Main Element" },
        ],
      },
      {
        title: "Forms and Inputs",
        description: "User input and validation",
        topics: [
          { title: "form Element" },
          { title: "input Types" },
          { title: "label Element" },
          { title: "textarea" },
          { title: "select" },
          { title: "button Types" },
          { title: "Required Attribute" },
          { title: "Autocomplete" },
        ],
      },
      {
        title: "Accessibility and Media",
        description: "Inclusive and media-rich markup",
        topics: [
          { title: "alt Attribute" },
          { title: "Figure and Figcaption" },
          { title: "ARIA Basics" },
          { title: "Landmark Roles" },
          { title: "Heading Hierarchy" },
          { title: "audio Element" },
          { title: "video Element" },
          { title: "source Element" },
        ],
      },
    ],
  },
  {
    name: "CSS",
    description: "Styling, layout systems, and responsive design",
    color: "#1572b6",
    icon: "Palette",
    sections: [
      {
        title: "Core CSS",
        description: "Fundamental styling concepts",
        topics: [
          { title: "Selectors" },
          { title: "Specificity" },
          { title: "Cascade" },
          { title: "Inheritance" },
          { title: "Box Model" },
          { title: "Display Property" },
          { title: "Position Property" },
          { title: "z-index" },
        ],
      },
      {
        title: "Layout",
        description: "Modern layout techniques",
        topics: [
          { title: "Flexbox" },
          { title: "Flex Direction" },
          { title: "Justify Content" },
          { title: "Align Items" },
          { title: "CSS Grid" },
          { title: "Grid Template Columns" },
          { title: "Gap" },
          { title: "Media Queries" },
        ],
      },
      {
        title: "Advanced Styling",
        description: "Animations and maintainability",
        topics: [
          { title: "Transitions" },
          { title: "Keyframes" },
          { title: "Transform" },
          { title: "Custom Properties" },
          { title: "Container Queries" },
          { title: "Pseudo-classes" },
          { title: "Pseudo-elements" },
          { title: "BEM Naming" },
        ],
      },
    ],
  },
  {
    name: "Browser APIs",
    description: "Web platform APIs commonly tested in frontend interviews",
    color: "#0ea5a4",
    icon: "Globe",
    sections: [
      {
        title: "DOM and Events",
        description: "Document interaction",
        topics: [
          { title: "DOM Tree" },
          { title: "querySelector" },
          { title: "Event Propagation" },
          { title: "Event Bubbling" },
          { title: "Event Capturing" },
          { title: "Event Delegation" },
          { title: "addEventListener" },
          { title: "MutationObserver" },
        ],
      },
      {
        title: "Storage and Networking",
        description: "Persistence and communication",
        topics: [
          { title: "localStorage" },
          { title: "sessionStorage" },
          { title: "Cookies" },
          { title: "Fetch API" },
          { title: "AbortController" },
          { title: "WebSocket" },
          { title: "Server-Sent Events" },
          { title: "CORS" },
        ],
      },
      {
        title: "Modern Web APIs",
        description: "Capabilities and background tasks",
        topics: [
          { title: "IntersectionObserver" },
          { title: "ResizeObserver" },
          { title: "History API" },
          { title: "URL API" },
          { title: "Clipboard API" },
          { title: "Geolocation API" },
          { title: "Web Workers" },
          { title: "Service Workers" },
        ],
      },
    ],
  },
  {
    name: "Performance",
    description: "Frontend performance engineering roadmap",
    color: "#22c55e",
    icon: "Gauge",
    sections: [
      {
        title: "Core Web Vitals",
        description: "User-centric metrics",
        topics: [
          { title: "Largest Contentful Paint" },
          { title: "Interaction to Next Paint" },
          { title: "Cumulative Layout Shift" },
          { title: "Time to First Byte" },
          { title: "First Contentful Paint" },
          { title: "Performance Budgets" },
          { title: "Lighthouse" },
          { title: "WebPageTest" },
        ],
      },
      {
        title: "Rendering and Loading",
        description: "Critical path optimization",
        topics: [
          { title: "Critical Rendering Path" },
          { title: "Render Blocking Resources" },
          { title: "Code Splitting" },
          { title: "Lazy Loading" },
          { title: "Prefetch" },
          { title: "Preload" },
          { title: "Image Optimization" },
          { title: "Font Optimization" },
        ],
      },
      {
        title: "Runtime Optimization",
        description: "JavaScript and UI performance",
        topics: [
          { title: "Long Tasks" },
          { title: "Main Thread Blocking" },
          { title: "Memoization" },
          { title: "List Virtualization" },
          { title: "Debounce" },
          { title: "Throttle" },
          { title: "Reflow" },
          { title: "Repaint" },
        ],
      },
    ],
  },
  {
    name: "System Design",
    description: "Frontend-focused system design fundamentals",
    color: "#14b8a6",
    icon: "Network",
    sections: [
      {
        title: "Design Foundations",
        description: "Thinking and tradeoffs",
        topics: [
          { title: "Functional Requirements" },
          { title: "Non-functional Requirements" },
          { title: "Scalability" },
          { title: "Reliability" },
          { title: "Availability" },
          { title: "Consistency" },
          { title: "Latency" },
          { title: "Throughput" },
        ],
      },
      {
        title: "Web Architecture",
        description: "Frontend architecture patterns",
        topics: [
          { title: "CDN" },
          { title: "Edge Caching" },
          { title: "SSR" },
          { title: "CSR" },
          { title: "SSG" },
          { title: "Hydration" },
          { title: "API Gateway" },
          { title: "BFF Pattern" },
        ],
      },
      {
        title: "Case Study Building Blocks",
        description: "Common interview scenarios",
        topics: [
          { title: "Design a News Feed" },
          { title: "Design a Chat UI" },
          { title: "Design a Notification System" },
          { title: "Design a Search Suggestion" },
          { title: "Design a File Upload Flow" },
          { title: "Pagination" },
          { title: "Infinite Scroll" },
          { title: "Optimistic UI" },
        ],
      },
    ],
  },
  {
    name: "Node.js (Frontend focused)",
    description: "Node.js concepts relevant for frontend engineers",
    color: "#65a30d",
    icon: "Server",
    sections: [
      {
        title: "Node Fundamentals",
        description: "Runtime essentials",
        topics: [
          { title: "What is Node.js?" },
          { title: "Event-driven Architecture" },
          { title: "Node Event Loop" },
          { title: "CommonJS" },
          { title: "ES Modules in Node" },
          { title: "package.json" },
          { title: "npm Scripts" },
          { title: "Environment Variables" },
        ],
      },
      {
        title: "Frontend Tooling",
        description: "Build and development workflows",
        topics: [
          { title: "Webpack Basics" },
          { title: "Vite Basics" },
          { title: "Babel" },
          { title: "esbuild" },
          { title: "Module Bundling" },
          { title: "Tree Shaking" },
          { title: "Source Maps" },
          { title: "Hot Module Replacement" },
        ],
      },
      {
        title: "Server Concepts for Frontend",
        description: "Server patterns frontend engineers should know",
        topics: [
          { title: "Express Basics" },
          { title: "REST Basics" },
          { title: "Middleware" },
          { title: "CORS Handling" },
          { title: "Proxy Setup" },
          { title: "Authentication Tokens" },
          { title: "SSR Server Basics" },
          { title: "Streaming Responses" },
        ],
      },
    ],
  },
  {
    name: "Testing",
    description: "Testing pyramid for frontend interviews",
    color: "#f97316",
    icon: "TestTube2",
    sections: [
      {
        title: "Testing Fundamentals",
        description: "Core testing principles",
        topics: [
          { title: "Testing Pyramid" },
          { title: "Unit Testing" },
          { title: "Integration Testing" },
          { title: "End-to-End Testing" },
          { title: "Arrange Act Assert" },
          { title: "Test Isolation" },
          { title: "Deterministic Tests" },
          { title: "Test Doubles" },
        ],
      },
      {
        title: "JavaScript and React Testing",
        description: "Frontend testing tools",
        topics: [
          { title: "Jest Basics" },
          { title: "Vitest Basics" },
          { title: "Mock Functions" },
          { title: "Module Mocking" },
          { title: "React Testing Library" },
          { title: "Queries by Role" },
          { title: "User Events" },
          { title: "Async Testing" },
        ],
      },
      {
        title: "E2E and Quality",
        description: "Confidence at system level",
        topics: [
          { title: "Playwright Basics" },
          { title: "Cypress Basics" },
          { title: "Test Flakiness" },
          { title: "Network Stubbing" },
          { title: "Accessibility Testing" },
          { title: "Visual Regression Testing" },
          { title: "Code Coverage" },
          { title: "CI Test Pipeline" },
        ],
      },
    ],
  },
] as const;
